# Generated by Django 2.1.7 on 2019-05-05 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rating.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(validators=[rating.models.validatePunutations])),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokes.Joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
