# Generated by Django 2.1.7 on 2019-03-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='joke',
            name='totalPuntuation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
