# Generated by Django 2.1.7 on 2019-04-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_commentjoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentjoke',
            name='joke',
        ),
        migrations.RemoveField(
            model_name='commentjoke',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentJoke',
        ),
    ]
