# Generated by Django 2.1.7 on 2019-03-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20190330_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='totalPuntuation',
            field=models.IntegerField(null=True),
        ),
    ]
