# Generated by Django 2.1.7 on 2019-03-31 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jokes', '0003_auto_20190330_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puntuation',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='puntuation',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='totalPuntuation',
        ),
        migrations.AddField(
            model_name='joke',
            name='countRates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joke',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='rating',
            table='Ratings',
        ),
    ]
