# Generated by Django 2.1.7 on 2019-03-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_auto_20190331_1806'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favouritejoke',
            table='favouriteJokes',
        ),
        migrations.AlterModelTable(
            name='joke',
            table='jokes',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
    ]
