# Generated by Django 2.1.7 on 2019-03-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_auto_20190331_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='countRates',
        ),
    ]
