# Generated by Django 2.1.7 on 2019-03-31 21:48

from django.db import migrations, models
import jokes.models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_remove_joke_countrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.FloatField(validators=[jokes.models.validatePunutations]),
        ),
    ]
