# Generated by Django 2.1.7 on 2019-03-11 22:53

from django.db import migrations, models
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=userAuth.models.user_directory_path, validators=[userAuth.models.validate_image]),
        ),
    ]
