# Generated by Django 2.1.7 on 2019-03-18 22:15

from django.db import migrations, models
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20190311_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to=userAuth.models.user_directory_path, validators=[userAuth.models.validate_image]),
        ),
    ]
