# Generated by Django 2.1.7 on 2019-03-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_auto_20190323_2131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
