# Generated by Django 2.1.7 on 2019-04-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0008_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resetPassword',
            field=models.URLField(null=True),
        ),
    ]
