# Generated by Django 2.1.7 on 2019-04-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_profile_resetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resetPassword',
        ),
    ]
